version: '3.8'

services:
  next:
    container_name: next
    image: luuppi.azurecr.io/${IMAGE}:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_HOST=redisDB
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - redisDB
    networks:
      - weba-network

  redisDB:
    container_name: redisDB
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      - weba-network

  postgresDB:
    container_name: postgresDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:16.0-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - '5433:5432'
    networks:
      - weba-network

volumes:
  postgres-data:

#
# External network handled by luuppi-proxy
# https://github.com/luuppiry/luuppi-proxy
#
networks:
  weba-network:
    external: true
